-- Mirrors the schema of the hosted "Jewelry Tracking" project (wrhogwcpzlakobovqnwm)
-- so the local dev database has the same tables/views for the Supabase VS Code extension.

create table public.item_type (
  code text primary key,
  name text not null unique,
  sort integer not null default 0
);

create table public.maker (
  id integer generated by default as identity primary key,
  name text not null unique
);

create table public.tier (
  code text primary key,
  name text not null unique,
  sort integer not null default 0
);

create table public.platform (
  id integer generated by default as identity primary key,
  name text not null unique,
  fee_pct numeric not null default 0,
  fixed_fee numeric not null default 0,
  note text
);

create table public.app_setting (
  key text primary key,
  value text,
  note text
);

create table public.piece (
  id integer generated by default as identity primary key,
  sku text not null unique,
  date_cataloged date,
  item_type_code text references public.item_type (code),
  description text,
  primary_materials text,
  size_length text,
  maker_id integer references public.maker (id),
  tier_code text references public.tier (code),
  condition text check (condition = any (array['Poor', 'Fair', 'Good', 'Very Good', 'Excellent', 'Needs Repair'])),
  repair_needed boolean default false,
  existing_tag_price numeric,
  asking_price numeric,
  photo_taken boolean default false,
  listing_status text not null default 'Not Listed' check (listing_status = any (array['Not Listed', 'Draft', 'Listed', 'Reserved', 'Sold'])),
  photo_file_note text,
  verification_note text,
  group_lot_note text,
  condition_detail text,
  repair_check_detail text,
  notes text,
  source text,
  original_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.piece_photo (
  id integer generated by default as identity primary key,
  piece_id integer not null references public.piece (id),
  file_name text not null,
  sort_order integer not null default 1
);

create table public.sale (
  id integer generated by default as identity primary key,
  piece_id integer not null references public.piece (id),
  sale_date date not null,
  platform_id integer references public.platform (id),
  gross_sale_price numeric not null default 0,
  shipping_charged numeric not null default 0,
  actual_fee_override numeric,
  actual_shipping_cost numeric not null default 0,
  other_costs numeric not null default 0,
  notes text,
  created_at timestamptz not null default now()
);

create table public.expense (
  id integer generated by default as identity primary key,
  expense_date date not null,
  category text,
  description text,
  amount numeric not null default 0,
  deduct_before_split boolean not null default false,
  notes text,
  created_at timestamptz not null default now()
);

create table public.payout (
  month_start date primary key,
  paid_to_bobby numeric,
  date_paid date,
  notes text
);

create table public.follow_up (
  id integer generated by default as identity primary key,
  piece_id integer not null references public.piece (id),
  open_question text,
  why_it_matters text,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.verification_check (
  id integer generated by default as identity primary key,
  check_name text not null unique,
  how_to text,
  what_it_changes text,
  pieces_affected_raw text,
  is_resolved boolean not null default false
);

create table public.piece_verification_check (
  piece_id integer not null references public.piece (id),
  check_id integer not null references public.verification_check (id),
  primary key (piece_id, check_id)
);

create table public.listing_disclosure (
  id integer generated by default as identity primary key,
  applies_to_raw text,
  disclosure_point text,
  recommended_wording text
);

create table public.piece_disclosure (
  piece_id integer not null references public.piece (id),
  disclosure_id integer not null references public.listing_disclosure (id),
  primary key (piece_id, disclosure_id)
);

create table public.lot_candidate (
  id integer generated by default as identity primary key,
  group_name text not null,
  pieces_raw text,
  why_grouped text,
  suggested_handling text
);

create table public.piece_lot (
  piece_id integer not null references public.piece (id),
  lot_id integer not null references public.lot_candidate (id),
  primary key (piece_id, lot_id)
);

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path to ''
as $$
begin new.updated_at = now(); return new; end
$$;

create trigger trg_piece_updated
  before update on public.piece
  for each row execute function public.set_updated_at();

alter table public.item_type enable row level security;
alter table public.maker enable row level security;
alter table public.tier enable row level security;
alter table public.platform enable row level security;
alter table public.app_setting enable row level security;
alter table public.piece enable row level security;
alter table public.piece_photo enable row level security;
alter table public.sale enable row level security;
alter table public.expense enable row level security;
alter table public.payout enable row level security;
alter table public.follow_up enable row level security;
alter table public.verification_check enable row level security;
alter table public.piece_verification_check enable row level security;
alter table public.listing_disclosure enable row level security;
alter table public.piece_disclosure enable row level security;
alter table public.lot_candidate enable row level security;
alter table public.piece_lot enable row level security;

create policy owner_all_item_type on public.item_type for all to authenticated using (true) with check (true);
create policy owner_all_maker on public.maker for all to authenticated using (true) with check (true);
create policy owner_all_tier on public.tier for all to authenticated using (true) with check (true);
create policy owner_all_platform on public.platform for all to authenticated using (true) with check (true);
create policy owner_all_app_setting on public.app_setting for all to authenticated using (true) with check (true);
create policy owner_all_piece on public.piece for all to authenticated using (true) with check (true);
create policy owner_all_piece_photo on public.piece_photo for all to authenticated using (true) with check (true);
create policy owner_all_sale on public.sale for all to authenticated using (true) with check (true);
create policy owner_all_expense on public.expense for all to authenticated using (true) with check (true);
create policy owner_all_payout on public.payout for all to authenticated using (true) with check (true);
create policy owner_all_follow_up on public.follow_up for all to authenticated using (true) with check (true);
create policy owner_all_verification_check on public.verification_check for all to authenticated using (true) with check (true);
create policy owner_all_piece_verification_check on public.piece_verification_check for all to authenticated using (true) with check (true);
create policy owner_all_listing_disclosure on public.listing_disclosure for all to authenticated using (true) with check (true);
create policy owner_all_piece_disclosure on public.piece_disclosure for all to authenticated using (true) with check (true);
create policy owner_all_lot_candidate on public.lot_candidate for all to authenticated using (true) with check (true);
create policy owner_all_piece_lot on public.piece_lot for all to authenticated using (true) with check (true);
